default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

AutonomousDriver:
    normalize: false
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2024
    buffer_size: 20240
    max_steps: 10e6
    summary_freq: 5000
    num_layers: 2
    hidden_units: 256
    behavioral_cloning:
        demo_path: ./demos/AutonomousDriver.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.995
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: ./demos/AutonomousDriver.demo